server:
  port: 8888

lucky:
  http-client:
    http-executor: http_client
    ignore-ssl-verify: true
    enable-cookie-manage: true
    cookie-store-generate:
      bean-name: cookieStore
    print-log-packages:
      - io.github.lucklike.springboothttp.api
    thread-pool-param:
      name-format: async-pool-
      core-pool-size: 5
      maximum-pool-size: 10
      blocking-queue-size: 20
    auto-redirect: true
    enable-content-compress: true
    spring-el-functions:
      - alias: join
        clazz: com.luckyframework.common.StringUtils
        method: format
        param-types:
          - java.lang.String
          - java.lang.Object[]
    spring-el-function-classes:
      - prefix: SF_
        clazz: io.github.lucklike.springboothttp.utils.SpELFunction
      - clazz: io.github.lucklike.springboothttp.api.FanYiGouApi
    spring-el-root-variables:
      appId: ${fanYiGou.config.appId}
      privateKey: ${fanYiGou.config.privateKey}
      nonceStr: ${fanYiGou.config.nonce_str}





API:
  location: http://localhost:8081
#  location: https://localhost
  simple: ${API.location}/simple
  cookie: ${API.location}/cookie
  user: ${API.location}/user
  file: ${API.location}/file
  java: ${API.location}/java

fanYiGou:
  appId: a94edf938ecd3a2a8ca013bd800b52ad
  privateKey: b2482869665723323117ea6d00de9818833788eecce62cbfe88f6baeb23eb08ef59031af1aece287fe54e8b6c383eb3f
  config:
    appId: "#{#SM4('${fanYiGou.appId}')}"
    privateKey: "#{#SM4('${fanYiGou.privateKey}')}"
    nonce_str: "#{#nanoId()}"
