server:
  port: 8888

lucky:
  http-client:
    http-executor: jdk
#    ignore-ssl-verify: true
    enable-cookie-manage: true
    cookie-manage-priority: 1001
    cookie-store-generate:
      bean-name: cookieStore
    print-log-packages:
      - io.github.lucklike.springboothttp.api
    enable-print-annotation-info: true
    enable-print-args-info: true
    print-log-priority: 10000
    thread-pool-param:
      name-format: http-pool-
      core-pool-size: 5
      maximum-pool-size: 10
      blocking-queue-size: 20
    auto-redirect: true
    redirect-priority: 101
    enable-content-compress: true
    spring-el-function-packages:
      - io.github.lucklike.springboothttp.api.spel.function
    spring-el-package-imports:
      - java.util
    add-allow-print-log-body-mime-types:
      - application/x-protobuf
    allow-print-log-body-max-length: 2048

#    accept-encoding: br, gzip
#    spring-el-functions:
#      - alias: join
#        clazz: com.luckyframework.common.StringUtils
#        method: format
#        param-types:
#          - java.lang.String
#          - java.lang.Object[]
#    spring-el-function-classes:
#      - clazz: io.github.lucklike.springboothttp.api.spel.function.SpELFunctionUtils










API:
  location: http://localhost:8081
#  location: https://localhost
  simple: ${API.location}/simple
  cookie: ${API.location}/cookie
  user: ${API.location}/user
  file: ${API.location}/file
  java: ${API.location}/java


download:
  folder: D:/cairh/download/files/

fanYiGou:
  sm4:
    appId: a94edf938ecd3a2a8ca013bd800b52ad
    privateKey: b2482869665723323117ea6d00de9818833788eecce62cbfe88f6baeb23eb08ef59031af1aece287fe54e8b6c383eb3f


en: 中文测试-Test

