server:
  port: 8888

lucky:
  http-client:
    http-executor: jdk
    ignore-ssl-verify: true
    enable-cookie-manage: true
    cookie-store-generate:
      bean-name: cookieStore
    print-log-packages:
      - io.github.lucklike.springboothttp.api
    thread-pool-param:
      name-format: async-pool-
      core-pool-size: 5
      maximum-pool-size: 10
      blocking-queue-size: 20
    auto-redirect: true




API:
#  location: http://localhost:8081
  location: https://localhost
  simple: ${API.location}/simple
  cookie: ${API.location}/cookie
  user: ${API.location}/user
  file: ${API.location}/file
  java: ${API.location}/java