server:
  port: 8888

lucky:
  http-client:
    print-log-packages:
      - io.github.lucklike.springboothttp.api.SimpleApi
    thread-pool-param:
      name-format: async-pool-
      core-pool-size: 5
      maximum-pool-size: 10
      blocking-queue-size: 20



API:
  location: https://localhost
  simple: ${API.location}/simple